version: '3'
services:
  app:
    container_name: app
    build: .
    ports:
      - '18000:8000'
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
    tty: true
    # django-adminが生成されない場合のため、コマンドにシンボリックリンクを作成する
    command: >
      bash -c "pip install -r /code/requirements.txt
      && if [ ! -e /usr/bin/django-admin ]; then ln -s /usr/local/lib/python3.8/site-packages/django/bin/django-admin.py /usr/bin/django-admin; fi
      && python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000
      && /bin/bash"
    depends_on:
      - db
    volumes:
      - ${APP_ROOT}:/code
      - python-packages:/usr/local/lib/python3.8/site-packages
  db:
    container_name: db
    image: postgres:10.7-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --locale=ja_JP.UTF-8'
      TZ: Asia/Tokyo
    ports:
      - '55432:5432'
    volumes:
      - server-db-data:/var/lib/postgresql/data
volumes:
  python-packages:
  server-db-data:
